Attribute VB_Name = "DemoChibiArc"
Option Explicit

' This module contains a series of demonstration routines for the ChibiArc class.
' The demos cover basic ZIP creation and extraction, CAB file creation, AES-256 encrypted archives, adding data from memory, and ISO mounting/dismounting.
' Note that the ISO mounting demo requires a valid ISO file to be present on the system.
' The code (and general debugging support and error handling) was generated by Gemini.

Public Sub RunAllDemos()
    Debug.Print "Starting ChibiArc Demos..."
    Debug.Print "=========================="
    Demo_BasicZip
    Demo_CABWrite
    Demo_AesEncryption
    Demo_InMemoryData
    Demo_ISOMounting    
    Debug.Print "=========================="
    Debug.Print "Demos complete! Check " & DEMO_ROOT & " for the output files."
End Sub

Private Property Get DEMO_ROOT() As String
    DEMO_ROOT = Environ$("TEMP") & "\ChibiArcDemo\"
End Property

Private Sub SetupDemoEnvironment()
    On Error Resume Next        
    MkDir DEMO_ROOT
    MkDir DEMO_ROOT & "source\"
    MkDir DEMO_ROOT & "extract\"
    On Error GoTo 0
    
    ' Create a couple of dummy files
    Dim ff As Integer
    ff = FreeFile
    Open DEMO_ROOT & "source\SampleText1.txt" For Output As #ff
    Print #ff, "This is a sample text file created for the ChibiArc demo."
    Print #ff, "It contains some basic ASCII text."
    Close #ff
    
    ff = FreeFile
    Open DEMO_ROOT & "source\SampleText2.txt" For Output As #ff
    Print #ff, "This is another sample file."
    Print #ff, "ChibiArc is highly performant and easy to use."
    Close #ff
End Sub

' ----------------------------------------------------------------------------
' 1. Basic ZIP Creation and Extraction
' ----------------------------------------------------------------------------
Public Sub Demo_BasicZip()
    SetupDemoEnvironment
    
    Dim arc As ChibiArc
    Dim zipPath As String
    Dim extractPath As String
    
    zipPath = DEMO_ROOT & "BasicArchive.zip"
    extractPath = DEMO_ROOT & "extract\basic\"
    
    ' -- WRITE --
    Set arc = New ChibiArc
    Debug.Print "--- Demo_BasicZip ---"
    
    If arc.NewFile(zipPath) Then
        ' Add an entire folder (recursive)
        arc.Add DEMO_ROOT & "source\"
        
        If arc.SaveFile() Then
            Debug.Print "Successfully created ZIP: " & zipPath
        Else
            Debug.Print "Failed to save ZIP. Error: " & arc.LastError
        End If
    End If
    Set arc = Nothing
    
    ' -- READ --
    Set arc = New ChibiArc
    If arc.OpenFile(zipPath) Then
        On Error Resume Next: MkDir extractPath: On Error GoTo 0
        
        If arc.ExtractAll(extractPath) Then
            Debug.Print "Successfully extracted to: " & extractPath
        Else
            Debug.Print "Failed to extract ZIP. Error: " & arc.LastError
        End If
        arc.CloseFile
    End If
    Set arc = Nothing
End Sub

' ----------------------------------------------------------------------------
' 2. CAB File Creation (using native Windows FCI)
' ----------------------------------------------------------------------------
Public Sub Demo_CABWrite()
    SetupDemoEnvironment
    
    Dim arc As ChibiArc
    Dim cabPath As String
    cabPath = DEMO_ROOT & "TestArchive.cab"
    
    Set arc = New ChibiArc
    Debug.Print "--- Demo_CABWrite ---"
    
    If arc.NewFile(cabPath) Then
        arc.Add DEMO_ROOT & "source\SampleText1.txt"
        arc.Add DEMO_ROOT & "source\SampleText2.txt"
        
        If arc.SaveFile() Then
            Debug.Print "Successfully created CAB: " & cabPath
        Else
            Debug.Print "Failed to save CAB. Error: " & arc.LastError
        End If
    End If
    Set arc = Nothing
End Sub

' ----------------------------------------------------------------------------
' 3. AES-256 Encrypted Archive
' ----------------------------------------------------------------------------
Public Sub Demo_AesEncryption()
    SetupDemoEnvironment
    
    Dim arc As ChibiArc
    Dim zipPath As String
    Dim extractPath As String
    Dim myPassword As String
    
    zipPath = DEMO_ROOT & "SecureArchive.zip"
    extractPath = DEMO_ROOT & "extract\secure\"
    myPassword = "SuperSecretPassword123!"
    
    ' -- WRITE --
    Set arc = New ChibiArc
    Debug.Print "--- Demo_AesEncryption ---"
    
    If arc.NewFile(zipPath) Then
        arc.Encryption = aeAes256
        arc.PassPhrase = myPassword
        
        arc.Add DEMO_ROOT & "source\SampleText1.txt"
        
        If arc.SaveFile() Then
            Debug.Print "Successfully created encrypted ZIP: " & zipPath
        Else
            Debug.Print "Failed to save encrypted ZIP. Error: " & arc.LastError
        End If
    End If
    Set arc = Nothing
    
    ' -- READ --
    Set arc = New ChibiArc
    ' Pass the password in OpenFile
    If arc.OpenFile(zipPath, myPassword) Then
        On Error Resume Next: MkDir extractPath: On Error GoTo 0
        
        If arc.ExtractAll(extractPath) Then
            Debug.Print "Successfully extracted encrypted ZIP to: " & extractPath
        Else
            Debug.Print "Failed to extract encrypted ZIP. Error: " & arc.LastError
        End If
        arc.CloseFile
    End If
    Set arc = Nothing
End Sub

' ----------------------------------------------------------------------------
' 4. Adding Data from Memory (Byte Arrays / Strings)
' ----------------------------------------------------------------------------
Public Sub Demo_InMemoryData()
    SetupDemoEnvironment
    
    Dim arc As ChibiArc
    Dim zipPath As String
    Dim myStringData As String
    Dim myByteArray() As Byte
    
    zipPath = DEMO_ROOT & "MemoryArchive.zip"
    myStringData = "This text was generated dynamically in memory and added directly to the archive without touching the disk first!"
    
    ' Convert string to byte array
    myByteArray = StrConv(myStringData, vbFromUnicode)
    
    Set arc = New ChibiArc
    Debug.Print "--- Demo_InMemoryData ---"
    
    If arc.NewFile(zipPath) Then
        ' You can add byte arrays directly by specifying a destination path in the archive
        arc.Add myByteArray, "DynamicData.txt"
        
        If arc.SaveFile() Then
            Debug.Print "Successfully saved ZIP containing in-memory data: " & zipPath
        Else
            Debug.Print "Failed to save ZIP. Error: " & arc.LastError
        End If
    End If
    Set arc = Nothing
End Sub

' ----------------------------------------------------------------------------
' 5. ISO Mounting and Dismounting (Requires an ISO file)
' ----------------------------------------------------------------------------
Public Sub Demo_ISOMounting()
    ' Note: This requires a valid ISO file to exist. We will just demonstrate
    ' the syntax here as we can't guarantee an ISO file is present.
    
    Dim arc As ChibiArc
    Dim isoPath As String
    Dim mountedDrive As String
    
    isoPath = "C:\Temp\SomeDiskImage.iso"
    
    ' Skip if file doesn't exist
    If Dir(isoPath) = "" Then
        Debug.Print "--- Demo_ISOMounting ---"
        Debug.Print "Skipping ISO demo: Test ISO not found at " & isoPath
        Exit Sub
    End If
    
    Set arc = New ChibiArc
    Debug.Print "--- Demo_ISOMounting ---"
    
    ' Mount the ISO
    mountedDrive = arc.MountISO(isoPath, True, True)
    
    If mountedDrive <> "" Then
        Debug.Print "Successfully mounted ISO to drive: " & mountedDrive
        Debug.Print "Directory contents of mounted drive:"
        Debug.Print Dir(mountedDrive & "*.*")
        
        ' Dismount
        arc.DismountISO
        Debug.Print "Dismounted ISO."
    Else
        Debug.Print "Failed to mount ISO. Error: " & arc.LastError
    End If
    
    Set arc = Nothing
End Sub

